### ISSUE TITLE
Make sure the peripherals are controllable with Zephyr

### ISSUE THREAD

**Issue by ikerperezdelpalomar** [CodethinkLabs/bloodlight-firmware#112]
- [x] Add support for turning LEDs on/off
- [x] Add USB support
  - [x] Test usb support in Zephyr
- [ ]  Make sure spi can be used.

Work happening in: https://github.com/CodethinkLabs/bloodlight-firmware/tree/ikerperez/zephyr-board-porting

**Comment by ikerperezdelpalomar** [comment]
Currently it's possible to use USB as STOUD, this can be proven by running the [zephyr/samples/subsys/usb/console](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/subsys/usb/console) test.

However when trying to run a more basic test (such as [zephyr/samples/helloworld](https://github.com/zephyrproject-rtos/zephyr/tree/master/samples/hello_world)) were devicetree APIs are not used to configure and enable USB like in the example above the laptop doesn't detect the bloodlight board, which makes me think that USB has not been enabled.

Next steps have to be:

1. Discover why this happens.
2. When the reason is discovered:
    1. If this happens because the DPPU bit in USB_BCDR register is not raised, sort it out. (Follow the steps described in the issue description.)
    2. If it's for a different reason evaluate if it is worth to work on it or if it is more worth to use the devicetreet APIs

In order to write a value to the register [HAL_PCD_DevConnect]() might help.

The next  might be helpful:

- [stm32g4xx_hal_pcd.c](https://github.com/zephyrproject-rtos/hal_stm32/blob/1e5111a2c146285aed9805e6816d172ff591c060/stm32cube/stm32g4xx/drivers/src/stm32g4xx_hal_pcd.c)
- [stm32g4xx_ll_usb.c](https://github.com/zephyrproject-rtos/hal_stm32/blob/master/stm32cube/stm32g4xx/drivers/src/stm32g4xx_ll_usb.c)

Taken from [stm32cube/stm32g4xx](https://github.com/zephyrproject-rtos/hal_stm32/tree/master/stm32cube/stm32g4xx)

**Comment by ikerperezdelpalomar** [comment]
Answer to point 1 on previous comment:


> Sample hello_world  does not use USB and so not enables it, and if hello_world would enable USB it would not be a simplest sample and thus not hello_world. There are few boards which enables USB on board level per default because this boards do not have a debug probe integrated and so depends on USB for logging or shell.

**Comment by ikerperezdelpalomar** [comment]
I used [zephyr/samples/susbsys/usb/console](https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/subsys/usb/console/src/main.c) to test the usb configuration. This way i found out that Zephyr expects the app to enable usb and not the usb driver, so this should be handled by us in the firmware. To enable usb [usb_enable()](https://docs.zephyrproject.org/apidoc/latest/group____usb__device__core__api_gad1fa5e491d93c2bd1fe7967c12148902.html) must be used. Some notes about this:

## Zephyr Release Notes 2.2
>USB
   The usb_enable() function, which was previously invoked automatically by the USB stack, now needs to be explicitly called by the application in order to enable the USB subsystem.
    The usb_enable() function now takes a parameter, usb_dc_status_callback which can be set by the application to a callback to receive status events from the USB stack. The parameter can also be set to NULL if no callback is required.

 [0]

## Zephyr Release Notes 2.4

> USB
    The usb_enable() function, which, for some samples, was invoked automatically on system boot up, now needs to be explicitly called by the application in order to enable the USB subsystem. If your application relies on any of the following Kconfig options, then it shall also enable the USB subsystem:
        :option:`CONFIG_USB_DEVICE_NETWORK_ECM`
        :option:`CONFIG_USB_DEVICE_NETWORK_EEM`
        :option:`CONFIG_USB_DEVICE_NETWORK_RNDIS`
        :option:`CONFIG_TRACING_BACKEND_USB`
        :option:`CONFIG_USB_UART_CONSOLE`

[1]

> 

- [0] [zephyr/doc/releases/release-notes-2.2.rst](https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/releases/release-notes-2.2.rst)
 - [1] [zephyr/doc/releases/release-notes-2.4.rst](https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/releases/release-notes-2.4.rst)

**Comment by ikerperezdelpalomar** [comment]
This issue will be discussed in https://github.com/CodethinkLabs/bloodlight-zephyr/issues/4 in the future

**Comment by tlsa** [comment]
Moved to here: https://github.com/CodethinkLabs/bloodlight-zephyr
