### ISSUE TITLE
Add support for reading ADCs using Zephyr

### ISSUE THREAD

**Issue by ikerperezdelpalomar** [CodethinkLabs/bloodlight-firmware#113]
- [x] Find out how Zephyr does dynamic pin allocation.
- [ ] Checkout the default pin setup in zephyr for stm32g and if needed apply changes to our devicetree to support adc and opamp.
- [ ] Decide if the dynamic pin allocation should be implemented at this stage or i future changes.

**Comment by ikerperezdelpalomar** [comment]
Bloodlight firmware allocates pins PA3, PB1 and PB2 dinamically for ADC or OPAM. In order to do the same in Zephyr I believe that the [pin mux driver](https://docs.zephyrproject.org/latest/reference/peripherals/pinmux.html) needs to be used.

There is an specific stm32 pinmux driver too: [pinmux_stm32.c](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pinmux/stm32/pinmux_stm32.c) .  So I wonder if the the pin mux driver would call this driver directly.

**Comment by ikerperezdelpalomar** [comment]
At the beginning I considered created a pinmux.c file that would contain all the pin allocations in one place. This I would involve creating the pinmux file listing the desired pins and configure them depending on the board revision. Then source.c file would need to be modified to use this file somehow (I still need to discover how to do that).

However, other possibility would be to replace the functions taken from linopencm3 with functions from zephyr. This approach would be a provisional solutions I believe, since the previous method is the one I see mostly being used in the zephyr project.

**Comment by ikerperezdelpalomar** [comment]
So far I have discovered that for the first approach the next would be needed:

- The pinmux.c content would be executed in the system initialization with [SYS_INIT()](https://github.com/zephyrproject-rtos/zephyr/blob/b6ad85cdd97e32dca8870151eeb0d8712a2398b6/include/init.h#L135). 
  - First I would need to set the pins with [pinmux_pin_set](https://docs.zephyrproject.org/latest/reference/peripherals/pinmux.html#c.pinmux_pin_set) 
    - I need to understand what are the [PINMUX_FUNCTIONS](https://github.com/zephyrproject-rtos/zephyr/blob/b6ad85cdd97e32dca8870151eeb0d8712a2398b6/include/drivers/pinmux.h#L29) .
   -  I need to create mux device pointing at a device tree pinmux definition and somehow relate. Like here: 
      - Device tree definition: https://github.com/zephyrproject-rtos/zephyr/blob/2134f9b72dc205ffb08aef5f2d9fc5cfacd58fee/dts/arm/atmel/samd2x.dtsi#L99
      -  Creation of the mux device in pinmux.c: https://github.com/zephyrproject-rtos/zephyr/blob/2134f9b72dc205ffb08aef5f2d9fc5cfacd58fee/boards/arm/atsamd21_xpro/pinmux.c#L13
  - Finally I somehow need to prove that what all this actually creates a relationship between the pins and the pin multiplexer.

**Comment by ikerperezdelpalomar** [comment]
So I found [pinmux_stm32g4x.h](https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/pinmux/stm32/pinmux_stm32g4x.h) file where it seems like the functions are described, however is clearly stated on it that all those macros are deprecated. So I don't know which is actually the way to go...

**Comment by ikerperezdelpalomar** [comment]
I decided to discard the pinmux approach, because I haven't been able to clarify the doubts described above  and even i posted some questions in various  channels in the Zephy's slack  workspace I was never replied.

**Comment by ikerperezdelpalomar** [comment]
When replacing the `gpio_mode_setup` for `gpio_stm32_configure` API I wasn't sure if I was going to be able to configure multiple pins in the same call, so I decided to first configure one at a time and once the firmware is up and running when can check whether that can be done.

**Comment by ikerperezdelpalomar** [comment]
stm32g4 series needs to be awaken from deep sleep mode, in the original firmware this was done using the [adc_disable_deeppwd](https://github.com/ben-brewer-codethink/libopencm3/blob/dd8b15de275eda2e2bfcf199c53a480e58bab8cf/lib/stm32/g4/adc.c#L689) api in the [acq.c](https://github.com/CodethinkLabs/bloodlight-firmware/blob/05ffb77231ab7e4c291024ff6d2e490206fb3997/firmware/src/acq/adc.c#L408) file.

Zephyrs [adc_stm32_init](https://github.com/zephyrproject-rtos/zephyr/blob/023491e6830235dd3ff869a63a24073e10cf59a6/drivers/adc/adc_stm32.c#L583) disables deep sleep mode for G4 family by default [here](https://github.com/zephyrproject-rtos/zephyr/blob/023491e6830235dd3ff869a63a24073e10cf59a6/drivers/adc/adc_stm32.c#L630), therefore I will delete lines 407 to 409.

**Comment by ikerperezdelpalomar** [comment]
It seems like I will need to modify completely the adc driver if I want to make it Zephyr style, to my understanding currently it's used the [bl_acq_adc_s](https://github.com/CodethinkLabs/bloodlight-firmware/blob/05ffb77231ab7e4c291024ff6d2e490206fb3997/firmware/src/acq/adc.c#L232) structure to hold the parameters that "describe" the adc, such as, base address, whether it's enabled or not, calibration etc. This is not based on devicetree in any way. On the other hand, zephyr uses devicetree for all this and has it's own [adc_stm32_data](https://github.com/zephyrproject-rtos/zephyr/blob/023491e6830235dd3ff869a63a24073e10cf59a6/drivers/adc/adc_stm32.c#L208)  and [adc_stm32_cfg](https://github.com/zephyrproject-rtos/zephyr/blob/023491e6830235dd3ff869a63a24073e10cf59a6/drivers/adc/adc_stm32.c#L223) structures to hold all those parameters.

**Comment by ikerperezdelpalomar** [comment]
I found two possible ways to adapt the adc support to Zephyr:

1. Stop using the adc APIs created in [adc.c](https://github.com/CodethinkLabs/bloodlight-firmware/blob/master/firmware/src/acq/adc.c) and implement the ones in zephyrs [adc driver](https://github.com/zephyrproject-rtos/zephyr/blob/master/include/drivers/adc.h). This might not be as straight forward as it looks, because I believe that zephyr adc driver doesn't perform exactly the same actions that are performed in the bloodlight driver. I need to double check this.

2. Replace the APIs taken from libopencm3 that are used in the bloddlight ADC driver by Zephyr's APIs. However, zephyr doesn't have (or I haven't found)  APIs with similar functionality as the ones from liboencm3 that bloodlight's uses, so workarounds would be needed to achieve the same results. Some of the missing APIs are:
    - [adc_enable_regulator and adc_disable_regulator](https://github.com/ben-brewer-codethink/libopencm3/blob/dd8b15de275eda2e2bfcf199c53a480e58bab8cf/lib/stm32/g4/adc.c#L702).
    - [nvic related](https://github.com/ben-brewer-codethink/libopencm3/blob/dd8b15de275eda2e2bfcf199c53a480e58bab8cf/lib/cm3/nvic.c)
    - [adc_set_multi_mode](https://github.com/ben-brewer-codethink/libopencm3/blob/dd8b15de275eda2e2bfcf199c53a480e58bab8cf/lib/stm32/g4/adc.c#L568)
    - Etc

I believe that the best option is to completely replace the bloodslight ADC driver by  zephyrs one, since this would reduce maintaining work and it would keep up to date with zephyrs firmware. However Ben Brewer was concerned about this and commented:

```
adc's can be statically configured to some degree probably
although it was always intended that it be dynamic since the configs change a lot, without looking at what device tree wants to make static, I'm not sure
```

**Comment by ikerperezdelpalomar** [comment]
After doing more research I found out thatthe APIs decribed above are not supported by zephyr but by the "zephyr ecosystem". That means that the "hal" drivers are included as modules and they can be used. So far the only when that is missing is `adc_set_multi_mode`.

**Comment by ikerperezdelpalomar** [comment]
I have been working on understanding the zephyr adc driver and I believe now that it performs very similarly to the current bloodlight adc driver. Therefore, I will proceed to adapt the current adc support to zephyr's adc driver.

**Comment by ikerperezdelpalomar** [comment]
Zephyr dma driver doesn't have [dma support](https://github.com/zephyrproject-rtos/zephyr/issues/17375#issuecomment-571513856) for now. Here I could work on a patch adding dma support, I could add the adc driver without dma or maybe a workaround could be done.

**Comment by tlsa** [comment]
Moved to here: https://github.com/CodethinkLabs/bloodlight-zephyr
