### ISSUE TITLE
Update libopencm3 for new chip (G4)

### ISSUE THREAD

**Issue by GeriG966** [CodethinkLabs/bloodlight-firmware#46]
Rev 1 uses an stm32f303 where rev 2 uses an stm32g474. There are a few hardware differences, and the code (specifically the libopencm3 code) may need changes to support these. We can make a start on this before the new hardware arrives based on the respective reference/programming manuals (although we can't test the changes work without hardware.)

**Comment by tlsa** [comment]
This is upstream's problem now.
